### ISSUE TITLE
`Transfer-Encoding: chunked` issues

### ISSUE THREAD

**Issue by rmccorm4** [geventhttpclient/geventhttpclient#158]
We have a [client library](https://github.com/triton-inference-server/client/blob/main/src/python/library/tritonclient/http/__init__.py) that uses `geventhttpclient` under the hood - and currently has the HTTP connection closed abruptly when a user adds the HTTP header: `Transfer-Encoding: chunked`.

The connection seems to be getting closed by geventhttpclient [here](https://github.com/geventhttpclient/geventhttpclient/blob/92bc5649a52b51df371a8704b58f3b78d55d2448/src/geventhttpclient/response.py#L193).

We are not doing anything special in our client to chunk the request data if this header is passed. **Does `geventhttpclient` expect the data it receives to be encoded as expected with this header, and if so is this documented anywhere? Or is this a bug?**

For comparison, we can send the same request with the same header using `urllib`, and **`urllib` will detect this HTTP header and chunk the data for us** as described in this `encode_chunked` parameter: https://docs.python.org/3/library/http.client.html#http.client.HTTPConnection.request

---

Here's a code example showing our use case and comparison:
```python
import urllib.request
from geventhttpclient import HTTPClient
from geventhttpclient.url import URL

def gevent_post(request_uri, request_body, headers={}):
    http = HTTPClient.from_url(request_uri)
    response = http.post(request_uri=request_uri,
                         body=request_body,
                         headers=headers)
    http.close()
    print(f"[gevent] Status Code: {response.status_code}")
    print(f"[gevent] Response: {response.read()}")

def urllib_post(request_uri, request_body, headers={}):
    req = urllib.request.Request(url=request_uri, headers=headers, data=request_body)
    with urllib.request.urlopen(req) as conn:
        response = conn.read().decode("utf8")
        status_code = conn.status
        print(f"[urllib] Status Code: {status_code}")
        print(f"[urllib] Response: {response}")

if __name__ == "__main__":
    request_uri = 'http://localhost:8000/v2/models/echo/infer'

    request_json = b'{"inputs":[{"name":"value","shape":[1,10],"datatype":"INT32","parameters":{"binary_data_size":40}}],"outputs":[{"name":"value","parameters":{"binary_data":true}}]}'
    json_size = len(request_json)

    binary_data = b'\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00'
    request_body = request_json + binary_data

    headers = {}
    headers["Inference-Header-Content-Length"] = str(json_size)
    headers["Transfer-Encoding"] = "chunked"

    try:
        gevent_post(request_uri, request_body, headers)
    except:
        traceback.print_exc()
        print("[gevent] ERROR: gevent closed connection")

    print("-"*80)

    urllib_post(request_uri, request_body, headers)
```
Output:
```
root@RMCCORMICK:/mnt/triton/jira/3704-http-chunked/chunked_repro# python gevent_example.py 
root@RMCCORMICK:/mnt/triton/jira/3704-http-chunked/chunked_repro# python gevent_example.py 
[gevent] Error: gevent closed connection
Traceback (most recent call last):
  File "gevent_example.py", line 40, in <module>
    gevent_post(request_uri, request_body, headers)
  File "gevent_example.py", line 8, in gevent_post
    response = http.post(request_uri=request_uri,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 272, in post
    return self.request(METHOD_POST, request_uri, body=body, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 260, in request
    raise e
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/client.py", line 253, in request
    response = HTTPSocketPoolResponse(sock, self._connection_pool,
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 298, in __init__
    super(HTTPSocketPoolResponse, self).__init__(sock, **kw)
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 170, in __init__
    self._read_headers()
  File "/usr/local/lib/python3.8/dist-packages/geventhttpclient/response.py", line 195, in _read_headers
    raise HTTPConnectionClosed(
geventhttpclient.response.HTTPConnectionClosed: connection closed.

--------------------------------------------------------------------------------

[urllib] Status Code: 200
[urllib] Response: {"model_name":"echo","model_version":"1","outputs":[{"name":"value","datatype":"INT32","shape":[1,10],"parameters":{"binary_data_size":40}}]}
```

**Comment by ml31415** [comment]
Hi @rmccorm4 ! Thanks for reporting this. Unfortunately chunked encoding is currently not implemented. But it's quite high up in the wish list.
